"""
Type stub for the MicroPython machine module.
IDE autocomplete only -- not uploaded to the board.
"""

from typing import Any


class Pin:
    IN: int
    OUT: int
    OPEN_DRAIN: int
    PULL_UP: int
    PULL_DOWN: int
    PULL_HOLD: int

    def __init__(self, id: str | int, mode: int = -1, pull: int = -1, *, value: int | None = None, drive: int = 0) -> None: ...
    def value(self, v: int | None = None) -> int: ...
    def on(self) -> None: ...
    def off(self) -> None: ...


class PWM:
    def __init__(self, pin: str | Pin, freq: int = 1000, *, duty_u16: int = 0, duty_ns: int = 0) -> None: ...
    def duty_u16(self, value: int) -> None: ...
    def freq(self, value: int) -> int: ...
    def deinit(self) -> None: ...


class UART:
    def __init__(self, id: int, *, baudrate: int = 115200, bits: int = 8, parity: int | None = None, stop: int = 1, tx: Any = None, rx: Any = None, timeout: int = 0, timeout_char: int = 0) -> None: ...
    def write(self, data: bytes | str) -> int: ...
    def read(self, nbytes: int = -1) -> bytes | None: ...
    def readline(self) -> bytes | None: ...
    def any(self) -> int: ...
    def readinto(self, buf: bytearray, nbytes: int = -1) -> int: ...


class I2C:
    def __init__(self, id: int, *, freq: int = 400000, scl: Any = None, sda: Any = None) -> None: ...
    def scan(self) -> list[int]: ...
    def writeto(self, addr: int, buf: bytes | bytearray, *, stop: bool = True) -> int: ...
    def readfrom(self, addr: int, nbytes: int, *, stop: bool = True) -> bytes: ...
    def readfrom_into(self, addr: int, buf: bytearray, *, stop: bool = True) -> int: ...


def unique_id() -> bytes: ...
def soft_reset() -> None: ...
def reset() -> None: ...
def freq() -> int: ...
