"""
Type stub for the seekfree smartcar module (built into RT1021 firmware).
IDE autocomplete only -- not uploaded to the board.
"""

from typing import Callable, Any

class encoder:
    def __init__(self, a_pin: str, b_pin: str, invert: bool = False) -> None: ...
    def get(self) -> int: ...

class ticker:
    def __init__(self, id: int = 0) -> None: ...
    def capture_list(self, *args: Any) -> None: ...
    def callback(self, fn: Callable[..., None]) -> None: ...
    def start(self, period_ms: int) -> None: ...
