"""
Type stub for the MicroPython time module.
IDE autocomplete only -- not uploaded to the board.
"""

def sleep(seconds: float) -> None: ...
def sleep_ms(ms: int) -> None: ...
def sleep_us(us: int) -> None: ...
def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_diff(end: int, start: int) -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def time() -> int: ...
def gmtime(secs: int | None = None) -> tuple[int, int, int, int, int, int, int, int]: ...
def localtime(secs: int | None = None) -> tuple[int, int, int, int, int, int, int, int]: ...
def mktime(t: tuple) -> int: ...
